### ISSUE TITLE
FEATURE make cookies optional

### ISSUE THREAD

**Issue by korthjp17** [dynamic/silverstripe-site-notifications#5]
**Is your feature request related to a problem? Please describe.**
Some violators or popups may need to stay visible after the first load.

**Describe the solution you'd like**
Possibly just adding a checkbox to PopUps and Violators to allow turning cookies off for each individual instance. Default would be on.

**Comment by muskie9** [comment]
@korthjp17 if this is still valid let's revisit in the next week or two.

**Comment by korthjp17** [comment]
I don't know if we have run into a good use-case for this, but I could see it as a nice feature. Open to thoughts though??
